### PR TITLE
feat: add reply value

### PR DESCRIPTION
**Pull request by msultanovdev**
Hello, I've added one prop to ReplyEditor component, which helps to set up default value to reply input.

### CODE REVIEW

**Comment by msultanovdev** [comment]
Hello! I've added one prop for defined initial root reply input. Thanks for your attention!

**Comment by fr4nzap** [comment]
Hey thanks for the PR!  I need to finish some core work and then I'll have a closer look. Is this just for the default value in the textarea?

**Comment by msultanovdev** [comment]
Hey! Yes, it is just for setting up default value in the textarea. I'll wait for your check, thanks!

**Comment by fr4nzap** [comment]
I totally forgot about this, my apologies! I'll consider it for the next round of fixes

**Comment by fr4nzap** [comment]
Implemented here: https://github.com/fr4nzap/zapthreads/commit/ac40f550e88bf74afbb22b096624b821733db307

**Pull request closed without merging**
